/**
 * Augments the generated Cloudflare `Env` interface with the secrets +
 * vars we declare in `wrangler.jsonc`. Keeps the generated
 * `worker-configuration.d.ts` untouched (it gets regenerated by
 * `wrangler types`), while still giving us typed `env.CPAY_*` access.
 */
interface Env {
  CPAY_CLIENT_KEY: string;
  CPAY_API_KEY: string;
  CPAY_SECRET: string;
  CPAY_INTEGRATION: string;
  CPAY_ENVIRONMENT?: ConvesioPayEnvironmentValue;
}

type ConvesioPayEnvironmentValue = "test" | "live";
